// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FB_WEB_KEY']!,
    appId: '1:74747522890:web:7b778c4ee13390a5ab1bb3',
    messagingSenderId: '74747522890',
    projectId: 'un-jour-un-mot-8b1f2',
    authDomain: 'un-jour-un-mot-8b1f2.firebaseapp.com',
    storageBucket: 'un-jour-un-mot-8b1f2.firebasestorage.app',
    measurementId: 'G-W25KBEZSK0',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FB_ANDROID_KEY']!,
    appId: '1:74747522890:android:6700ddf5b391d5b3ab1bb3',
    messagingSenderId: '74747522890',
    projectId: 'un-jour-un-mot-8b1f2',
    storageBucket: 'un-jour-un-mot-8b1f2.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FB_IOS_KEY']!,
    appId: '1:773293791946:ios:b20ab4389795a19fce3233',
    messagingSenderId: '773293791946',
    projectId: 'un-jour-un-mot-3f092',
    storageBucket: 'un-jour-un-mot-3f092.firebasestorage.app',
    iosClientId:
        '773293791946-lg3al3kavf382cnel8ks38sjb4vl6hum.apps.googleusercontent.com',
    iosBundleId: 'com.example.unJourUnMot',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FB_MACOS_KEY']!,
    appId: '1:773293791946:ios:b20ab4389795a19fce3233',
    messagingSenderId: '773293791946',
    projectId: 'un-jour-un-mot-3f092',
    storageBucket: 'un-jour-un-mot-3f092.firebasestorage.app',
    iosClientId:
        '773293791946-lg3al3kavf382cnel8ks38sjb4vl6hum.apps.googleusercontent.com',
    iosBundleId: 'com.example.unJourUnMot',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FB_WINDOWS_KEY']!,
    appId: '1:773293791946:web:42d054ceafee89e7ce3233',
    messagingSenderId: '773293791946',
    projectId: 'un-jour-un-mot-3f092',
    authDomain: 'un-jour-un-mot-3f092.firebaseapp.com',
    storageBucket: 'un-jour-un-mot-3f092.firebasestorage.app',
    measurementId: 'G-Q6VNPQ67JL',
  );
}
